mysql:
  host: "127.0.0.1"
  port: 3306
  user: "an9ryfr09"
  password: "yl83115$"
  charset: "utf8"
  parseTime: true
  location: "Local"
  db:
  - "dyrs_cms"
  - "dyrs_photo"
redis:
  host: "127.0.0.1"
  port: 6379
  auth: "yl83115$"
  Protocol: "tcp"
  Db: 0
http:
  host: ""
  port: 8316
  read_timeout: 30
  write_timeout: 30
  max_header_bytes: 1048576